test_batch_size: 100
batch_size: 256
num_microbatches: 256
lr: 0.001
momentum: 0.9
decay: 5e-4
dp: False
epochs: 120
save_on_epochs: [60, 119]
criterion: mse

#mu: 1.0
#ds_size: 70000

save_model: True
dataset: dsprites
model: regressionnet
scheduler: False
optimizer: Adam

root_dir: /projects/grail/jpgard/dsprites

multi_gpu: False