test_batch_size: 100
batch_size: 128
num_microbatches: 128
lr: 0.0001
momentum: 0.9
decay: 5e-4
#S: 1
#z: 1.0
dp: False
epochs: 60
save_on_epochs: [10, 20, 50]

mu: 1.0
ds_size: 70000

save_model: True
dataset: lfw
model: PretrainedRes
freeze_pretrained_weights: False
scheduler: False
optimizer: Adam

target_colname: Smiling
attribute_colname: Black
root_dir: /projects/grail/jpgard/lfw/
label_threshold: 0.3

multi_gpu: False