test_batch_size: 100
batch_size: 256
num_microbatches: 256
lr: 0.0001
momentum: 0.9
decay: 5e-4
dp: False
epochs: 240
save_on_epochs: [10, 50, 100, 150, 200, 239]

mu: 1.0

ds_size: 10000

# Note: 0 = airplane, 3 = cat, 5 = dog, 8 = ship
minority_group_keys: [3, 5]  # Should be a subset of the positive and/or negative class keys.
positive_class_keys: [0, 3]  # These keys are grouped into the class with label 1.
negative_class_keys: [5, 8]  # These keys are grouped into the class with label 0.
fixed_n_train: 10000
number_of_entries_test: 1000

save_model: True
dataset: cifar10
model: PretrainedRes
freeze_pretrained_weights: False
optimizer: Adam
scheduler: False

count_norm_cosine_per_batch: False

csigma: 0.9