test_batch_size: 100
batch_size: 256
num_microbatches: 256
lr: 0.01
momentum: 0.5
decay: 0
S: 5
z: 0.2
dp: True
epochs: 240
save_on_epochs: [10, 50, 100, 150, 200, 239]

mu: 1.0

ds_size: 10000

# Note: 0 = airplane, 1=automobile, 2 = bird, 3 = cat, 5 = dog, 8 = ship, 9=truck
minority_group_keys: [1, 9]  # Should be a subset of the positive and/or negative class keys.
positive_class_keys: [0, 1]  # These keys are grouped into the class with label 1.
negative_class_keys: [9, 2]  # These keys are grouped into the class with label 0.
fixed_n_train: 10000
number_of_entries_test: 1000
optimizer: SGD

save_model: True
dataset: cifar10
model: FlexiNet
scheduler: False

count_norm_cosine_per_batch: False

csigma: 0.9