test_batch_size: 100
batch_size: 256
num_microbatches: 256
lr: 0.01
momentum: 0.5
decay: 0
S: 1
z: 0.8
dp: True
epochs: 120
save_on_epochs: [10, 50, 100, 110]

mu: 1.0
ds_size: 11500

minority_group_keys: [1, 8]  # Should be a subset of the positive and/or negative class keys.
positive_class_keys: [1, 3]  # These keys are grouped into the class with label 1.
negative_class_keys: [7, 8]  # These keys are grouped into the class with label 0.
fixed_n_train: 11500
number_of_entries_test: 1000
optimizer: SGD

save_model: False
dataset: mnist
model: net
scheduler: False

count_norm_cosine_per_batch: False

csigma: 0.9