test_batch_size: 100
batch_size: 128
num_microbatches: 128
lr: 0.0001
momentum: 0.9
decay: 5e-4
S: 1
z: 1.0
dp: True
epochs: 60
save_on_epochs: [10, 20, 50]

mu: 1.0
ds_size: 70000

save_model: True
dataset: celeba
model: PretrainedRes
freeze_pretrained_weights: True
scheduler: False
optimizer: Adam

target_colname: Smiling
attribute_colname: Blond_Hair
attr_subset: 0
root_dir: /projects/grail/jpgard/celeba/img/img_align_celeba
attr_file: /projects/grail/jpgard/celeba/anno/list_attr_celeba.txt
eval_partition_file: /projects/grail/jpgard/celeba/eval/list_eval_partition.txt

multi_gpu: False