test_batch_size: 25
batch_size: 32
num_microbatches: 16
lr: 0.1
momentum: 0.9
decay: 5e-4
S: 1
z: 0.5
dp: True
epochs: 60
save_on_epochs: [5, 10, 50, 100, 200]

mu: 0.9
ds_size: 32000

key_to_drop: 5
number_of_entries: 500
number_of_entries_test: 1000

save_model: False
dataset: inat
model: inception
densenet_depth: 100
scheduler: True
