test_batch_size: 100
batch_size: 128
num_microbatches: 256
lr: 0.00005
momentum: 0.9
decay: 5e-4
S: 1
z: 1.0
dp: True
epochs: 300
save_on_epochs: [10, 50, 100, 150, 200, 250]

mu: 1.0
ds_size: 70000

save_model: True
dataset: celeba
model: PretrainedRes
scheduler: False
optimizer: Adam

target_colname: Smiling
root_dir: /projects/grail/jpgard/celeba/img/img_align_celeba
attr_file: /projects/grail/jpgard/celeba/anno/list_attr_celeba.txt
eval_partition_file: /projects/grail/jpgard/celeba/eval/list_eval_partition.txt

multi_gpu: False