# Parameters for grouped binary regression experiments (e.g. 8-3-vs-1-7).

test_batch_size: 100
batch_size: 256
num_microbatches: 256
lr: 0.01
momentum: 0.5
decay: 0

# Instead of computing the noise variance sigma = Z * s,
# since we are not using clipping (Z is undefined/infinite),
# we can explicitly set sigma.
S: inf
#sigma: 1
alpha: 1  # Setting alpha to None will cause training to default to using (non-adaptive) sigma.
adaptive_sigma: True
z: 0.8
dp: True
epochs: 60
save_on_epochs: [10, 50, 100, 200]

mu: 1.0
ds_size: 60000

#resumed_model: model_utk_May.16_15.10.07/model_last.pt.tar

grouped_mnist_task: True

key_to_drop: [3, 1]  # This will also be used as the 'minority group' in binary tasks.
positive_class_keys: [3, 8]  # These keys are grouped into the class with label 1.
negative_class_keys: [1,7]  # These keys are grouped into the class with label 0.
number_of_entries: 500   # This is the sample size of the minority keys specified in key_to_drop.
number_of_entries_test: 1000
optimizer: SGD
criterion: mse

save_model: False
dataset: mnist
model: regressionnet
densenet_depth: 100
scheduler: False
multi_gpu: False


count_norm_cosine_per_batch: False

csigma: 0.9